version: '3.9'
services:
  postgres:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nest
    networks:
      - nest-postgres
networks:
  nest-postgres:
